name: build-and-test-differential

on:
  workflow_call:
    secrets:
      codecov-token:
        required: true
    inputs:
      container:
        required: true
        type: string
      above:
        required: true
        type: boolean
      rosdistro:
        default: humble
        required: false
        type: string
      run-condition:
        default: true
        required: false
        type: boolean

env:
  CC: /usr/lib/ccache/gcc
  CXX: /usr/lib/ccache/g++

jobs:
  build-and-test-differential:
    name: build-and-test-diff
    if: ${{ inputs.run-condition }}
    runs-on: ubuntu-latest
    container: ${{ inputs.container }}
    steps:
      - name: Set PR fetch depth
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"
        shell: bash

      - name: Checkout PR branch and all PR commits
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}

      - name: Show disk space before the tasks
        if: ${{ always() }}
        run: df -h
        shell: bash

      - name: Show machine specs
        run: lscpu && free -h
        shell: bash

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get modified packages
        id: get-modified-packages
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@v1

      - name: Use ros2-testing packages
        run: |
          if [ "${{ inputs.rosdistro }}" = "jazzy" ]; then
            sed -i 's|http://packages.ros.org/ros2/ubuntu|http://packages.ros.org/ros2-testing/ubuntu|g' /etc/apt/sources.list.d/ros2.sources
            apt-get update
          fi
        shell: bash

      - name: Create ccache directory
        run: |
          mkdir -p ${CCACHE_DIR}
          du -sh ${CCACHE_DIR} && ccache -s
        shell: bash

      - name: Attempt to restore ccache
        uses: actions/cache/restore@v5
        with:
          path: |
            /root/.ccache
          key: ccache-main-${{ runner.arch }}-${{ inputs.rosdistro }}${{ inputs.above && '-above' || '' }}-${{ github.event.pull_request.base.sha }}
          restore-keys: |
            ccache-main-${{ runner.arch }}-${{ inputs.rosdistro }}${{ inputs.above && '-above' || '' }}-

      - name: Limit ccache size
        run: |
          rm -f "${CCACHE_DIR}/ccache.conf"
          echo -e "# Set maximum cache size\nmax_size = 900MB" >> "${CCACHE_DIR}/ccache.conf"
        shell: bash

      - name: Show ccache stats before build and reset stats
        run: |
          du -sh ${CCACHE_DIR} && ccache -s
          ccache --zero-stats
        shell: bash

      - name: Build
        if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-build@v1
        with:
          rosdistro: ${{ inputs.rosdistro }}
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          cache-key-element: build-and-test-diff${{ inputs.above && '-above' || '' }}
          packages-above-repos: ${{ inputs.above && 'packages_above.repos' || '' }}
          underlay-workspace: /opt/autoware

      - name: Show ccache stats after build
        if: ${{ always() }}
        run: du -sh ${CCACHE_DIR} && ccache -s
        shell: bash

      - name: Test
        id: test
        if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-test@v1
        with:
          rosdistro: ${{ inputs.rosdistro }}
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          underlay-workspace: /opt/autoware

      - name: Upload coverage to CodeCov
        if: ${{ steps.test.outputs.coverage-report-files != '' && !inputs.above }}
        uses: codecov/codecov-action@v4
        with:
          files: ${{ steps.test.outputs.coverage-report-files }}
          fail_ci_if_error: false
          verbose: true
          flags: differential-${{ inputs.rosdistro }}
          token: ${{ secrets.codecov-token }}

      - name: Show disk space after the tasks
        run: df -h
        shell: bash

  clang-tidy-differential:
    name: clang-tidy-diff
    needs: build-and-test-differential
    if: ${{ (inputs.above == false) && inputs.run-condition }}
    runs-on: ubuntu-latest
    container: ${{ inputs.container }}
    steps:
      - name: Set PR fetch depth
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"

      - name: Checkout PR branch and all PR commits
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}

      - name: Show disk space before the tasks
        run: df -h

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get modified packages
        id: get-modified-packages
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@v1

      - name: Get changed files (existing files only)
        id: get-changed-files
        run: |
          echo "changed-files=$(git diff --name-only "origin/${{ github.base_ref }}"...HEAD | grep -E '\.(cpp|hpp)$' | while read -r file; do [ -e "$file" ] && echo -n "$file "; done)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Run clang-tidy
        if: ${{ steps.get-changed-files.outputs.changed-files != '' }}
        uses: autowarefoundation/autoware-github-actions/clang-tidy@v1
        with:
          rosdistro: ${{ inputs.rosdistro }}
          cache-key-element: build-and-test-diff${{ inputs.above && '-above' || '' }}
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          target-files: ${{ steps.get-changed-files.outputs.changed-files }}
          clang-tidy-config-url: https://raw.githubusercontent.com/autowarefoundation/autoware/main/.clang-tidy-ci
          underlay-workspace: /opt/autoware
          artifact-name: clang-tidy-result-${{ inputs.rosdistro }}

      - name: Show disk space after the tasks
        run: df -h
